# Generated by Django 4.0.2 on 2022-02-14 15:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ecom', '0009_comments'),
    ]

    operations = [
        migrations.AddField(
            model_name='comments',
            name='item',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ecom.product'),
        ),
    ]
